name: Compile Mod
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  lint-and-compile:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: "7.0.x"
      - run: dotnet restore ${{ github.event.repository.name }}.sln
      - uses: justalemon/VersionPatcher@v0.5.1
        with:
          version: 1.9.3.${{ github.run_number }}
          use-tag: true
          csproj-files: "**/root.props"
      - run: dotnet build ${{ github.event.repository.name }}.sln -c ${{ matrix.configuration }}
        working-directory: ${{ env.GITHUB_WORKSPACE }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.configuration }}
          path: bin/${{ matrix.configuration }}
